// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountLimits) DeepCopyInto(out *AccountLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountLimits.
func (in *AccountLimits) DeepCopy() *AccountLimits {
	if in == nil {
		return nil
	}
	out := new(AccountLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTConfig) DeepCopyInto(out *JWTConfig) {
	*out = *in
	if in.OperatorSeedSecret != nil {
		in, out := &in.OperatorSeedSecret, &out.OperatorSeedSecret
		*out = new(OperatorSeedSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTConfig.
func (in *JWTConfig) DeepCopy() *JWTConfig {
	if in == nil {
		return nil
	}
	out := new(JWTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccount) DeepCopyInto(out *NatsAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccount.
func (in *NatsAccount) DeepCopy() *NatsAccount {
	if in == nil {
		return nil
	}
	out := new(NatsAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountList) DeepCopyInto(out *NatsAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountList.
func (in *NatsAccountList) DeepCopy() *NatsAccountList {
	if in == nil {
		return nil
	}
	out := new(NatsAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountSpec) DeepCopyInto(out *NatsAccountSpec) {
	*out = *in
	out.AuthConfigRef = in.AuthConfigRef
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(AccountLimits)
		**out = **in
	}
	if in.ExistingSeedSecret != nil {
		in, out := &in.ExistingSeedSecret, &out.ExistingSeedSecret
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountSpec.
func (in *NatsAccountSpec) DeepCopy() *NatsAccountSpec {
	if in == nil {
		return nil
	}
	out := new(NatsAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountStatus) DeepCopyInto(out *NatsAccountStatus) {
	*out = *in
	out.JWTSecretRef = in.JWTSecretRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountStatus.
func (in *NatsAccountStatus) DeepCopy() *NatsAccountStatus {
	if in == nil {
		return nil
	}
	out := new(NatsAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAuthConfig) DeepCopyInto(out *NatsAuthConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAuthConfig.
func (in *NatsAuthConfig) DeepCopy() *NatsAuthConfig {
	if in == nil {
		return nil
	}
	out := new(NatsAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAuthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAuthConfigList) DeepCopyInto(out *NatsAuthConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsAuthConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAuthConfigList.
func (in *NatsAuthConfigList) DeepCopy() *NatsAuthConfigList {
	if in == nil {
		return nil
	}
	out := new(NatsAuthConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsAuthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAccountRef) DeepCopyInto(out *NatsAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAccountRef.
func (in *NatsAccountRef) DeepCopy() *NatsAccountRef {
	if in == nil {
		return nil
	}
	out := new(NatsAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAuthConfigRef) DeepCopyInto(out *NatsAuthConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAuthConfigRef.
func (in *NatsAuthConfigRef) DeepCopy() *NatsAuthConfigRef {
	if in == nil {
		return nil
	}
	out := new(NatsAuthConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAuthConfigSpec) DeepCopyInto(out *NatsAuthConfigSpec) {
	*out = *in
	out.ServerAuthConfig = in.ServerAuthConfig
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAuthConfigSpec.
func (in *NatsAuthConfigSpec) DeepCopy() *NatsAuthConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NatsAuthConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsAuthConfigStatus) DeepCopyInto(out *NatsAuthConfigStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsAuthConfigStatus.
func (in *NatsAuthConfigStatus) DeepCopy() *NatsAuthConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NatsAuthConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUser) DeepCopyInto(out *NatsUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUser.
func (in *NatsUser) DeepCopy() *NatsUser {
	if in == nil {
		return nil
	}
	out := new(NatsUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserList) DeepCopyInto(out *NatsUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NatsUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserList.
func (in *NatsUserList) DeepCopy() *NatsUserList {
	if in == nil {
		return nil
	}
	out := new(NatsUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NatsUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserSpec) DeepCopyInto(out *NatsUserSpec) {
	*out = *in
	out.AuthConfigRef = in.AuthConfigRef
	if in.AccountRef != nil {
		in, out := &in.AccountRef, &out.AccountRef
		*out = new(NatsAccountRef)
		**out = **in
	}
	if in.PasswordFrom != nil {
		in, out := &in.PasswordFrom, &out.PasswordFrom
		*out = new(PasswordSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(Permissions)
		(*in).DeepCopyInto(*out)
	}
	if in.ExistingSeedSecret != nil {
		in, out := &in.ExistingSeedSecret, &out.ExistingSeedSecret
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserSpec.
func (in *NatsUserSpec) DeepCopy() *NatsUserSpec {
	if in == nil {
		return nil
	}
	out := new(NatsUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsUserStatus) DeepCopyInto(out *NatsUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsUserStatus.
func (in *NatsUserStatus) DeepCopy() *NatsUserStatus {
	if in == nil {
		return nil
	}
	out := new(NatsUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorSeedSecretRef) DeepCopyInto(out *OperatorSeedSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorSeedSecretRef.
func (in *OperatorSeedSecretRef) DeepCopy() *OperatorSeedSecretRef {
	if in == nil {
		return nil
	}
	out := new(OperatorSeedSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSource) DeepCopyInto(out *PasswordSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSource.
func (in *PasswordSource) DeepCopy() *PasswordSource {
	if in == nil {
		return nil
	}
	out := new(PasswordSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerAuthConfigRef) DeepCopyInto(out *ServerAuthConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerAuthConfigRef.
func (in *ServerAuthConfigRef) DeepCopy() *ServerAuthConfigRef {
	if in == nil {
		return nil
	}
	out := new(ServerAuthConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Permissions) DeepCopyInto(out *Permissions) {
	*out = *in
	if in.PublishAllow != nil {
		in, out := &in.PublishAllow, &out.PublishAllow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PublishDeny != nil {
		in, out := &in.PublishDeny, &out.PublishDeny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubscribeAllow != nil {
		in, out := &in.SubscribeAllow, &out.SubscribeAllow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubscribeDeny != nil {
		in, out := &in.SubscribeDeny, &out.SubscribeDeny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Permissions.
func (in *Permissions) DeepCopy() *Permissions {
	if in == nil {
		return nil
	}
	out := new(Permissions)
	in.DeepCopyInto(out)
	return out
}
